AWSTemplateFormatVersion: "2010-09-09"
Description:
  EC2 Instances
Parameters:
  ImageId:
    Type: String
    Default: ami-0522ab6e1ddcc7055
    AllowedValues:
      - ami-0522ab6e1ddcc7055
      - ami-0e53db6fd757e38c7

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      KeyName: ubuntu
      Tags:
        - Key: Name
          Value: Ec2
  
  NewVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC