AWSTemplateFormatVersion: "2010-09-09"
Description:
  EC2 Instances
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Compute configuration"
        Parameters: 
          - Ec2Params
      -        
        Label: 
          default: "Storage"
        Parameters: 
          - S3bucket

Parameters:
  S3bucket:
    Type: String
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9_-]*'

  Ec2Params:
    Type: String
    Default: ami-0522ab6e1ddcc7055
    AllowedValues:
      - ami-0522ab6e1ddcc7055
      - ami-0e53db6fd757e38c7

Resources:
  Rocklinbucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: rocklinbucket
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref Ec2Params
      InstanceType: t2.micro
      KeyName: ubuntu
      Tags:
        - Key: Name
          Value: Ec2
  
  NewVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC