AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 instance"

Parameters: 
  InstanceTypeParameter: 
    Description: Select instance type
    Type: String
    Default: t2.micro
   

Resources: 
  Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-0892a9c01908fafd1
      Tags: 
        - Key: Name
          Value: cf-demo

Outputs:
    InstanceName:
      Value: !Ref Instance
    DNSName:
      Value: RockinDns