AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 instance"

Parameters: 
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
      - qa

Mappings:
  EnvMap: #logical id/map name
    dev:
      instanceType: "t2.micro"
      name: "dev"

    qa:
      instanceType: "t2.micro"
      name: "qa"

    prod:
      instanceType: "t2.micro"
      name: "prod"


Resources: 
  Instance: #logical id/name
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !FindInMap [EnvMap, !Ref Environment, instanceType]
      ImageId:  ami-0522ab6e1ddcc7055
      Tags: 
        - Key: "Name"
          Value: !FindInMap [EnvMap, !Ref Environment, name]

Outputs:
  InstanceName:
    Value: !Ref Instance