AWSTemplateFormatVersion: "2010-09-09"
Description: "Export Values"

Parameters: 
  InstanceTypeParameter: 
    Description: Select instance type
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro

Resources: 
  Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-0892a9c01908fafd1
      AvailabilityZone: !Select 
                        - 8
                        - !GetAZs 
                          Ref: 'AWS::Region'

Outputs:
  InstanceAvl:
      Value: !GetAtt Instance.AvailabilityZone
      Description: Availibility Zone
      Export:
        Name: "AvailZone"

  InstanceId:
      Value: !Ref Instance
      Description: Instance information
      Export:
        Name: "Instance"